import Link from 'next/link';
export const metadata = { title: 'Data & privacy — WorkProof' };
export const dynamic = 'force-dynamic';
export default function Page() {
  return <main className="main privacy-page"><Link href="/profile" className="text-button">← Back to Profile</Link><div className="page-intro"><div className="eyebrow">YOUR EVIDENCE, YOUR CONTROL</div><h1>Data & privacy</h1><p>How this version of WorkProof handles your information.</p></div>
    <section className="profile-info"><h2>What WorkProof stores</h2><p>Your sign-in account identifier, original experience text, selected context and date, reviewed claims, corrections and any reference descriptions or links you add. Verification requests also store worker and recipient details, a snapshot of the shared evidence, and any response, identity, relationship, basis and timestamp.</p>
      <h2>Why it is stored</h2><p>To let you save and reopen your evidence, trace career wording to its sources, export it, and ask a person you choose to verify a selected fact. The application does not create employee rankings, employer activity dashboards or advertising profiles.</p>
      <h2>Processing and providers</h2><p>This version extracts evidence with rules and templates in your browser. It does not send experience text to an external AI model. Sign-in and hosting use OpenAI Sites; application records are stored in its Cloudflare D1 database. Hosting and identity providers may process operational information under their own policies. Reference URLs are not automatically fetched by WorkProof; opening one takes you to that third-party service.</p>
      <h2>What other people can see</h2><p>Your Evidence Bank is account-specific. A verification recipient can see only the snapshot you preview and approve. That includes the selected claim and source, context, date, limitations and relevant references. Sponsorship does not automatically expose your history. Career Pack sharing is a separate action: review its exact text before sending a copy.</p>
      <h2>Drafts, exports and shared devices</h2><p>An unfinished draft is held in this browser tab’s session storage, keyed to your account. It is not a cloud backup and can disappear when the tab is closed. Saved records are kept in the application database until you delete them. Exports and shared copies are outside WorkProof’s control. Avoid entering customer identifiers, payment details or confidential workplace material.</p>
      <h2>Deletion and withdrawal</h2><p>Profile contains “Delete my WorkProof data”. Each saved experience also has its own deletion control. Deletion removes the selected application data and requests from the active database; it cannot recall copies another person already received. Deleting all data also removes responses you gave as a verifier and invalidates those confirmations. Your ChatGPT identity is managed separately and is not deleted by WorkProof.</p>
      <h2>Before public release</h2><p>This is an implementation disclosure for the private pilot, not a completed public-release privacy policy. The operator’s support contact, provider retention and backup details, account deletion arrangements and App Store privacy declarations must be confirmed before public release.</p>
      <Link href="/profile" className="button">Manage my data</Link>
    </section></main>;
}
